### PR TITLE
Add Grape route information

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
Sources the templated path for the requested Grape route for the rack operation name.

### CODE REVIEW

**Review by keitwb — APPROVED** [review]
I don't know anything about Grape, but nothing stands out as wrong to me.

**Review by mpetazzoni — APPROVED** [review]
LGTM. Does this generate route names that include the HTTP method? Usually we want those only in the `http.method` tag (https://github.com/signalfx/signalfx-instrumentor-docs/blob/master/names-tags-and-logs.md#L94).

**Comment by rmfitzpatrick** [comment]
> LGTM. Does this generate route names that include the HTTP method? Usually we want those only in the `http.method` tag (https://github.com/signalfx/signalfx-instrumentor-docs/blob/master/names-tags-and-logs.md#L94).

No, it's just the templated path and the response* content type (by apparent Grape convention).

**Comment by mpetazzoni** [comment]
Thanks for clarifying. Got confused by the test.

**Pull request merged**
